### ISSUE TITLE
Error: Expecting a single string value: [type=closure; extent=1]

### ISSUE THREAD

**Issue by fab4ap** [ecohealthalliance/fasterize#13]
Hello: Wanted to report this error. Hope the foll. is self-explanatory. Works with rasterize() but not in fasterize().

> library(fasterize)
> library(sf)
> library(raster)
> riv129mprdsf = st_read(dsn=".", layer="prdall_riv129_20k129")
Simple feature collection with 129084 features and 25 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -4278174 ymin: 3802881 xmax: 3161826 ymax: 10742880
epsg (SRID):    NA
proj4string:    +proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs_

> class(riv129mprdsf)
[1] "sf"         "data.frame"

> canus1kgrd
class       : RasterLayer 
dimensions  : 6940, 7440, 51633600  (nrow, ncol, ncell)
resolution  : 1000, 1000  (x, y)
extent      : -4282964, 3157036, 3808483, 10748483  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 
data source : in memory
names       : canus20kgrdsync 
values      : 0, 128710  (min, max)

> act = fasterize(riv129mprdsf, canus1kgrd, field="riv129_20k", fun=mean, background=0)
Error in fasterize(riv129mprdsf, canus1kgrd, field = "riv129_20k", fun = mean) : 
  Expecting a single string value: [type=closure; extent=1].

**Comment by mdsumner** [comment]
What the error is saying is that `mean` is not an allowed value for "fun" - it must be a

```R
?fasterize
#character. The name of a function by which to combine overlapping polygons. Currently takes "sum", #"first", "last", "min", "max", "count", or "any".
```

You can apply a mean at all currently, but there's a workaround for using raster for this in the help.

**Comment by noamross** [comment]
I'm closing this as it is expected behavior, but opened #18, #19, and #20 in response.

**Comment by fab4ap** [comment]
OK. Thanks much!
Prasad
