### ISSUE TITLE
fasterize linestring?

### ISSUE THREAD

**Issue by elgabbas** [ecohealthalliance/fasterize#30]
Hello,

Does the `fasterize` package also work with `sf` LINESTRING objects?
I tried to use the function, but it gives me this error:
```
Error in fasterize(sf = st_as_sf(Sh1), raster = MaskLayer2_5, field = "id",  : 
  Not compatible with requested type: [type=character; target=double].
```

Thanks

**Comment by greenLauren** [comment]
Also see this issue thread: https://github.com/ecohealthalliance/fasterize/issues/1

**Comment by mdsumner** [comment]
closing because covered by older issue
