### ISSUE TITLE
Can fun = "mean" be added?

### ISSUE THREAD

**Issue by johnForne** [ecohealthalliance/fasterize#43]
Kia ora 
I'm looking to use the fasterize() and am impressive at how much quicker it seems to be than the equivalent rasterize(). However, I'd like to be able to fasterize() using fun = "mean". I gather from the help that summarising by different functions maybe possible using `by=` to get a RasterBrick, etc. However, I'm unclear how to do this in practice. Providing an example, could be helpful? That said, I also wonder whether a more performant option would be to simply extend the range of functions able to be taken.

Do you have any plans/timeframe for adding mean function?

Thanks

**Comment by mdsumner** [comment]
see #18 closing because this already on the wishlist
